  spring:
    application:
      name: LifeFragmentShop
    web:
      error:
        include-message: always
        include-stacktrace: always
        include-exception: true
    datasource:
      url: jdbc:mysql://localhost:3306/lifefragmentshop?useSSL=false&serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
